
name: Validar archivo changelog.md


on:
  pull_request:

jobs:
  validar-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar si changelog.md fue modificado
        run: |
          git fetch origin ${{ github.head_ref }}
          if git diff --name-only origin/${{ github.base_ref }}..${{ github.head_ref }} | grep -q 'changelog.md'; then
            echo "::success::El archivo changelog.md fue modificado en el PR."
          else
            echo "::error::El archivo changelog.md no ha sido modificado en el PR."
            exit 1
          fi
