
name: Validar archivo changelog.md

on:
  pull_request:

jobs:
  validar-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validar existencia y actualización del archivo changelog.md
        uses: actions/github-script@v7
        with:
          script: |
            console.log('archivos:', context.payload.pull_request);
            const modifiedFiles = context.payload.pull_request.files.filter(file => file.status === 'modified');
            const changelog = modifiedFiles.find(file => file.filename === 'docs/changelog.md');
            if (!changelog) {
              core.setFailed("El archivo 'docs/changelog.md' no ha sido modificado en este pull request o no existe.");
            }
