name: Validar archivo changelog.md

on:
  pull_request:

jobs:
  validar-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validar archivo changelog.md
        run: |
          # Verifica si el archivo existe
          if [ ! -f "docs/changelog.md" ]; then
            echo "::error::El archivo 'docs/changelog.md' no existe."
            exit 1
          fi

          # Verifica si el archivo ha sido modificado
          if git diff --name-only HEAD^..HEAD | grep -q "docs/changelog.md"; then
            # El archivo ha sido modificado
            echo "Changelog actualizado!"
          else
            echo "::error::El archivo 'docs/changelog.md' no ha sido modificado en este pull request."
            exit 1
          fi
