name: Validar Changelog

on:
  pull_request:
    paths:
      - 'docs/changelog.md'
      
jobs:
  validar-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Validar existencia de changelog.md
      run: |
        if [ ! -f docs/changelog.md ]; then
          echo "Error: El archivo changelog.md no existe en la carpeta docs."
          exit 1
        fi

    - name: Validar cambios en changelog.md
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^docs/changelog.md$'; then
          echo "Changelog.md modificado en el Pull Request."
        else
          echo "Error: No se ha modificado changelog.md en el Pull Request."
          exit 1
        fi
