name: Validar archivo changelog.md

on:
  pull_request:

jobs:
  validar-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validar archivo changelog.md
        run: |
          # Verifica si el archivo existe
          if [ ! -f "docs/changelog.md" ]; then
            echo "::error::El archivo 'docs/changelog.md' no existe."
            exit 1
          fi

      - name: Validar archivo changelog.md
        run: |
          # Verifica si el archivo ha sido modificado
          files=$(git diff origin/develop...FETCH_HEAD --name-only | jq -r '.[]')
          for file in $files; do
            echo "Archivo: $file"
          done
          exit 1
