name: Changelog Check

on:
  pull_request:

jobs:
  changelog-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if changelog.md exists
        run: |
          if [[ ! -f "changelog.md" ]]; then
            echo "ERROR: changelog.md file not found!"
            exit 1
          fi
