name: Obtener archivos modificados

on:
  pull_request:


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Obtener archivos modificados
      run: |
        git fetch origin ${pull_request.head.sha}
        git diff origin/${pull_request.base.sha}...${pull_request.head.sha} --name-only > modified_files.txt

    - name: Mostrar archivos modificados
      run: cat modified_files.txt

